services:
  - type: web
    name: fastapi-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host=0.0.0.0 --port=3000
    envVars:
      - key: GOOGLE_CLIENT_ID
        value: your_value_here
      - key: GOOGLE_CLIENT_SECRET
        value: your_value_here
      - key: DATABASE_URL
        fromDatabase:
          name: your-db-name
          property: connectionString
